name: MesureAndGenerate

on:
  workflow_dispatch
  #schedule:
  #  # every ~30min (every 30min starting min13, every hour, ...)
  #  - cron:  '13/30 * * * *'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  mesure:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: sudo apt update && sudo apt -y install libsodium-dev cmake gnuplot

    #- name: Configure CMake
    #  run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    #- name: Build
    #  run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4 -t tomato

    #- name: Determine tag name
    #  id: tag
    #  shell: bash
    #  # taken from llama.cpp
    #  run: |
    #    SHORT_HASH="$(git rev-parse --short=7 HEAD)"
    #    if [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
    #      echo "name=dev-${SHORT_HASH}" >> $GITHUB_OUTPUT
    #    else
    #      SAFE_NAME=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')
    #      echo "name=dev-${SAFE_NAME}-${SHORT_HASH}" >> $GITHUB_OUTPUT
    #    fi

    #- name: Compress artifacts
    #  shell: bash
    #  run: |
    #    tar -czvf ${{ github.event.repository.name }}-${{ steps.tag.outputs.name }}-${{ runner.os }}-ubuntu20.04-x86_64.tar.gz -C ${{github.workspace}}/build/bin/ .

    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ github.event.repository.name }}-${{ steps.tag.outputs.name }}-${{ runner.os }}-ubuntu20.04-x86_64
    #    # TODO: do propper packing
    #    path: |
    #      ${{github.workspace}}/${{ github.event.repository.name }}-${{ steps.tag.outputs.name }}-${{ runner.os }}-ubuntu20.04-x86_64.tar.gz

  generate:
    if: ${{github.ref == 'refs/heads/master'}}

    runs-on: ubuntu-latest

    needs:
      - mesure

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    #- name: Determine tag name
    #  id: tag
    #  shell: bash
    #  # taken from llama.cpp
    #  run: |
    #    SHORT_HASH="$(git rev-parse --short=7 HEAD)"
    #    if [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
    #      echo "name=dev-${SHORT_HASH}" >> $GITHUB_OUTPUT
    #    else
    #      SAFE_NAME=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')
    #      echo "name=dev-${SAFE_NAME}-${SHORT_HASH}" >> $GITHUB_OUTPUT
    #    fi

    #- name: Download artifacts
    #  id: download-artifact
    #  uses: actions/download-artifact@v4
    #  with:
    #    path: ./artifacts/

    #- name: Create release
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    tag: ${{ steps.tag.outputs.name }}
    #  shell: bash
    #  run: |
    #    gh release create "$tag" \
    #        --repo="$GITHUB_REPOSITORY" \
    #        --title="${tag#v}" \
    #        --notes="preview build of the latest commit" \
    #        --prerelease

    #- name: Upload artifacts
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    tag: ${{ steps.tag.outputs.name }}
    #  shell: bash
    #  run: |
    #    ls -laR ./artifacts
    #    gh release upload "$tag" ./artifacts/*/* \
    #        --repo="$GITHUB_REPOSITORY"

