name: MesureAndGenerate

on:
  workflow_dispatch
  schedule:
    # every ~30min (every 30min starting min13, every hour, ...)
    - cron:  '13/30 * * * *'

#permissions:
#  contents: write

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  mesure_and_gen:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{secrets.PAT}}

    - name: Install Dependencies
      run: sudo apt update && sudo apt -y install git libsodium-dev cmake gnuplot

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/tool_src/build -DCMAKE_BUILD_TYPE=Release -S tool_src

    # TODO: cache
    - name: Build
      run: cmake --build ${{github.workspace}}/tool_src/build --config Release -j 4 -t dht_tool

    - name: run
      run: ${{github.workspace}}/tool_src/build/bin/dht_tool ${{github.workspace}}/docs/data

    - name: plot_all
      run: |
        cd ${{github.workspace}}/plot
        cat ../docs/data/* > plot.csv
        gnuplot -e "set terminal pngcairo size 1600,900; set output \"allsimple.png\"" allsimple.gnuplot
        mv allsimple.png ../docs/img/

    - name: commit and push update
      run: |
        git config --global user.name 'Green Sky'
        git config --global user.email 'Green-Sky@users.noreply.github.com'
        cd ${{github.workspace}}
        git add docs/data/
        git add docs/img/
        git status
        git commit -m "[automated] new datapoint"
        git push

